[agent]
  interval = "10s"
  flush_interval = "10s"
  skip_processors_after_aggregators = false
  omit_hostname = true

[[inputs.file]]
  files = ["/datasets/aa1.txt"]
  data_format = "xml"
  name_override = "liebert_ac"

  [inputs.file.tags]
    equipo = "aa1"
    ip = "192.168.6.1"

  [[inputs.file.xpath]]
    metric_selection = "//Item"

    [inputs.file.xpath.tags]
      item_id = "@id"
      item_name = "@name"
      label = "Label"
      unit = "Unit"

    [inputs.file.xpath.fields]
      value_num = "number(Value)"
      value_str = "string(Value)"

[[inputs.file]]
  files = ["/datasets/aa2.txt"]
  data_format = "xml"
  name_override = "liebert_ac"

  [inputs.file.tags]
    equipo = "aa2"
    ip = "192.168.6.2"

  [[inputs.file.xpath]]
    metric_selection = "//Item"

    [inputs.file.xpath.tags]
      item_id = "@id"
      item_name = "@name"
      label = "Label"
      unit = "Unit"

    [inputs.file.xpath.fields]
      value_num = "number(Value)"
      value_str = "string(Value)"

[[inputs.file]]
  files = ["/datasets/aa3.txt"]
  data_format = "xml"
  name_override = "liebert_ac"

  [inputs.file.tags]
    equipo = "aa3"
    ip = "192.168.6.3"

  [[inputs.file.xpath]]
    metric_selection = "//Item"

    [inputs.file.xpath.tags]
      item_id = "@id"
      item_name = "@name"
      label = "Label"
      unit = "Unit"

    [inputs.file.xpath.fields]
      value_num = "number(Value)"
      value_str = "string(Value)"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "$INFLUX_TOKEN"
  organization = "$INFLUX_ORG"
  bucket = "$INFLUX_BUCKET"
